
[package]
name = "thor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = { version = "2.5.0", default-features = false }
async-lock = { version = "3.4.1", default-features = false }
async-trait = "0.1.89"
bitflags = "2.9.0"
cpio_reader = "0.1.2"
goblin = { version = "0.10.1", default-features = false, features = ["alloc", "elf32", "elf64", "endian_fd"] }
hashbrown = "0.16.0"
intrusive-collections = "0.9.7"
rlsf = "0.2.1"
seq-macro = "0.3.6"
spin = "0.10.0"
